defaults:
  linkConfig:
    create: true
    force: false
link:
  ~/.profile:
    path: profile
  ~/.vimrc:
    path: vim/vimrc
  ~/.bashrc:
  ~/.bash_logout:
  ~/.gitconfig:
  ~/.Xmodmap:
  ~/.Xresources:
  ~/.xinitrc:
  ~/.xprofile:

