defaults:
  linkConfig:
    create: true
    force: false
link:
  ~/.profile:
    path: profile
  ~/.vimrc:
    path: vim/vimrc
  ~/.bashrc:
    force: true
  ~/.gitconfig:
  ~/.Xmodmap:
  ~/.Xresources:
  ~/.xinitrc:
  ~/.xprofile:

