defaults:
    linkConfig:
      create: true
      force: true
      relink: true
link:
    ~/.profile:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.bash_logout:
    ~/.gitconfig:
    ~/.Xmodmap:
    ~/.Xresources:
    ~/.xinitrc:
        force: false
    ~/.xprofile:
    ~/.vimrc:
        path:  vim/
    ~/.i3/config:
        path: config/i3
    ~/.config/redshift.conf:
        path: config/redshift
    ~/.config/ranger/rc.conf:
        path: config/ranger
dirs:
    - ~/downloads
    - ~/usbmount

