name: dothask
version: '1.0.0'
synopsis: Dotfile setup utility
description: |
  Dotfile setup automation written in Haskell.
  You can find the documentation at https://github.com/bee/dothask#readme

homepage: https://github.com/bee/dothask#readme
bug-reports: https://github.com/bee/dothask/issues
category: CLI, config, configuration, linux
author: Bee Ellis
maintainer: Bee Ellis <bellis8099@gmail.com>
github: bee/dothask
copyright: 2020 Bee Ellis
license: MIT
license-file: LICENSE

extra-source-files:
  - README.md
  - example.config.yaml

dependencies:
  - base ^>= 4.13.0.0
  - yaml ^>= 0.11.3.0
  - text ^>= 1.2.3.2
  - turtle ^>= 1.5.19
  - unordered-containers ^>= 0.2.10.0
  - optparse-applicative ^>= 0.15.1.0
  - unix ^>= 2.7.2.2

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates

executables:
  dothask:
    main: Main.hs
    source-dirs:
      - app/
      - src/
    ghc-options:
      - -threaded
      - -rtsopts
tests:
  ghci-test:
    main: Spec.hs
    source-dirs:
      - test/
      - src/
    ghc-options:
      - -threaded
    dependencies:
      - hspec ^>= 2.7.1
      - QuickCheck ^>= 2.13.2
