name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        enable-stack: true

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack

    - name: Install dependencies
      run: |
        stack upgrade
        stack update
        stack build --ghc-options="fPIC -fllvm" --only-dependencies --bench --test  --fast -j 9
    - name: Build
      run: |
        stack build --bench --test
    - name: Run tests
      run: stack test
